In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(f"/kaggle/input/data-csv/50_Startups.csv")
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
x,y

(array([[165349.2, 136897.8, 471784.1, 'New York'],
        [162597.7, 151377.59, 443898.53, 'California'],
        [153441.51, 101145.55, 407934.54, 'Florida'],
        [144372.41, 118671.85, 383199.62, 'New York'],
        [142107.34, 91391.77, 366168.42, 'Florida'],
        [131876.9, 99814.71, 362861.36, 'New York'],
        [134615.46, 147198.87, 127716.82, 'California'],
        [130298.13, 145530.06, 323876.68, 'Florida'],
        [120542.52, 148718.95, 311613.29, 'New York'],
        [123334.88, 108679.17, 304981.62, 'California'],
        [101913.08, 110594.11, 229160.95, 'Florida'],
        [100671.96, 91790.61, 249744.55, 'California'],
        [93863.75, 127320.38, 249839.44, 'Florida'],
        [91992.39, 135495.07, 252664.93, 'California'],
        [119943.24, 156547.42, 256512.92, 'Florida'],
        [114523.61, 122616.84, 261776.23, 'New York'],
        [78013.11, 121597.55, 264346.06, 'California'],
        [94657.16, 145077.58, 282574.31, 'New York'],
        [91749.1

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [3])],
    remainder="passthrough"
)
x = np.array(ct.fit_transform(x))

In [5]:
# split dataset into  train and test data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, test_size=0.2)
x_train, x_test, y_train, y_test

(array([[0.0, 1.0, 0.0, 55493.95, 103057.49, 214634.81],
        [0.0, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
        [0.0, 1.0, 0.0, 75328.87, 144135.98, 134050.07],
        [1.0, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
        [0.0, 1.0, 0.0, 91749.16, 114175.79, 294919.57],
        [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
        [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
        [0.0, 0.0, 1.0, 1000.23, 124153.04, 1903.93],
        [0.0, 0.0, 1.0, 542.05, 51743.15, 0.0],
        [0.0, 0.0, 1.0, 65605.48, 153032.06, 107138.38],
        [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
        [0.0, 1.0, 0.0, 61994.48, 115641.28, 91131.24],
        [1.0, 0.0, 0.0, 63408.86, 129219.61, 46085.25],
        [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
        [1.0, 0.0, 0.0, 23640.93, 96189.63, 148001.11],
        [1.0, 0.0, 0.0, 76253.86, 113867.3, 298664.47],
        [0.0, 0.0, 1.0, 15505.73, 127382.3, 35534.17],
        [0.0, 0.0, 1.0, 120542.52, 148718.95, 3

In [6]:
# train the model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [7]:
y_predict = regressor.predict(x_test)
np.set_printoptions(precision=2)
y_predict

array([103015.2 , 132582.28, 132447.74,  71976.1 , 178537.48, 116161.24,
        67851.69,  98791.73, 113969.44, 167921.07])

In [8]:
predicted_and_real_profit = np.concatenate((y_predict.reshape(len(y_predict), 1), y_test.reshape(len(y_test), 1)), axis=1)
print(predicted_and_real_profit)

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
